version: '3.8'
services:
  web_a:
    container_name: web_a_prod
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "8080:8080"
    environment:
      WEATHER_API_KEY: "mysupersecret"
    depends_on:
      - observability
      - web_b
  web_b:
    container_name: web_b_prod
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "8090:8080"
    environment:
      WEATHER_API_KEY: "mysupersecret"
    depends_on:
      - observability
  observability:
    container_name: observability
    image: openzipkin/zipkin
    ports:
      - "9411:9411"